config/routes.rb
CronMonitor::Engine.routes.draw do
  root to: "categories#index"
  resources :events
  resources :categories
end

app/models/cron_monitor/application_record.rb
module CronMonitor
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/cron_monitor/category.rb
module CronMonitor
  class Category < ApplicationRecord
    
    enum time_frame: {
      minute: 1,
      hour: 2,
      day: 3,
      week: 4,
      month: 5,
      year: 6
    }

    has_many :events, dependent: :delete_all

    validate :validate_time_interval_and_frame

    def self.select_with_last_start_and_finish_events_created_at
      all.select("cron_monitor_categories.*, (SELECT MAX(cron_monitor_events.created_at) FROM cron_monitor_events WHERE cron_monitor_events.category_id = cron_monitor_categories.id AND cron_monitor_events.kind = 1) as last_start_event_created_at, (SELECT MAX(cron_monitor_events.created_at) FROM cron_monitor_events WHERE cron_monitor_events.category_id = cron_monitor_categories.id AND cron_monitor_events.kind = 2) as last_finish_event_created_at").group("cron_monitor_categories.id")
    end

    def check_alarm

      return if !has_alarm?

      notify_failure_alarms if !is_running_properly?

    end

    def notify_start_or_finish(kind: , data: nil)

      data_in_string = data.map{|k,v| "#{k}: #{v}"}.join(" | ") if data.present?

      CronMonitor.alarm_notifiers.each do |notifier|

        notifier.new(I18n.translate("cron_monitor.starting_or_finishing.#{kind}", title: self.title, datetime: Time.current.to_s, data: data_in_string, locale: CronMonitor.i18n), kind: kind).perform!

      end

    end

    def has_alarm?

      self.time_frame.present? && self.time_interval.present?

    end

    def is_running_properly?(last_finish_event_created_at: self.events.finish.last.try(:created_at))

      raise ArgumentError.new("This monitor doesn't have any alarm") unless has_alarm?

      if !should_have_run_yet? || (last_finish_event_created_at && last_finish_event_created_at > should_have_finished_after)

        true

      else

        false

      end

    end

    def should_have_run_yet?

      should_have_finished_after > self.created_at

    end

    def should_have_finished_after

      should_have_finished_after = self.time_interval.send(self.time_frame.to_sym).ago

    end

    private

      def notify_failure_alarms

        CronMonitor.alarm_notifiers.each do |notifier|

          notifier.new(failure_message, kind: :failure).perform!

        end

      end

      def failure_message

        message = I18n.translate(
          "cron_monitor.starting_or_finishing.failure",
          title: self.title,
          should_have_run: I18n.translate(
            "cron_monitor.starting_or_finishing.should_have_run",
            should_have_run_after: I18n.localize(self.should_have_finished_after),
            ran_at_or_never_ran: self.events.finish.last.try(:created_at).blank? ? I18n.translate("cron_monitor.starting_or_finishing.it_never_ran") : I18n.translate("cron_monitor.starting_or_finishing.last_ran_at", datetime: I18n.localize(self.events.finish.last.try(:created_at).to_datetime.in_time_zone)),
            locale: CronMonitor.i18n
          ),
          locale: CronMonitor.i18n
        )

      end

      def validate_time_interval_and_frame

        if (self.time_frame.present? && self.time_interval.blank?) || (self.time_frame.blank? && self.time_interval.present?)

          self.errors.add(:base, "Time frame and time interval must both be informed (or none)")

        end

      end

  end
end

app/models/cron_monitor/event.rb
module CronMonitor
  
  class Event < ApplicationRecord

    belongs_to :category

    serialize :data, JSON

    enum kind: {
      start: 1,
      finish: 2
    }

    before_save :ensure_id_hash

    private

    def ensure_id_hash

      self.uuid ||= SecureRandom.uuid

    end

  end

end

app/controllers/cron_monitor/application_controller.rb
module CronMonitor
  class ApplicationController < ActionController::Base
    
    protect_from_forgery with: :exception

    around_action :switch_locale
     
    private

    def switch_locale(&action)
      locale = CronMonitor.i18n || I18n.default_locale
      I18n.with_locale(locale, &action)
    end

  end
end

app/controllers/cron_monitor/categories_controller.rb
require_dependency "cron_monitor/application_controller"

module CronMonitor
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:edit, :update, :destroy]

    # GET /categories
    def index
      @categories = Category.all
      # @categories = Category.all
      @categories = CronMonitor::Category.left_joins(:events).select_with_last_start_and_finish_events_created_at.order("last_start_event_created_at desc")
    end

    # GET /categories/1
    def show
      @category = Category.where(id: params[:id]).select_with_last_start_and_finish_events_created_at.take
      @events = @category.events.order(created_at: :desc)
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to @category, notice: 'Category was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Category was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Category was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def category_params
        params.require(:category).permit(:title, :description, :time_interval, :time_frame)
      end
  end
end

app/controllers/cron_monitor/events_controller.rb
require_dependency "cron_monitor/application_controller"

module CronMonitor
  class EventsController < ApplicationController
    before_action :set_event, only: [:show, :edit, :update, :destroy]

    # GET /events
    def index
      @events = Event.all
    end

    # GET /events/1
    def show
    end

    # GET /events/new
    def new
      @event = Event.new
    end

    # GET /events/1/edit
    def edit
    end

    # POST /events
    def create
      @event = Event.new(event_params)

      if @event.save
        redirect_to @event, notice: 'Event was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /events/1
    def update
      if @event.update(event_params)
        redirect_to @event, notice: 'Event was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /events/1
    def destroy
      @event.destroy
      redirect_to events_url, notice: 'Event was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_event
        @event = Event.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def event_params
        params.require(:event).permit(:category_id, :data)
      end
  end
end

app/helpers/cron_monitor/application_helper.rb
module CronMonitor
  module ApplicationHelper
  end
end

app/helpers/cron_monitor/categories_helper.rb
module CronMonitor
  module CategoriesHelper
  end
end

app/helpers/cron_monitor/events_helper.rb
module CronMonitor
  module EventsHelper
  end
end

app/views/cron_monitor/categories/_category_shared_columns.html.erb
<td><%= category.title %></td>
<td><%= category.description %></td>
<td>
  <% if category.last_start_event_created_at.present? %>
    <%= I18n.localize(category.last_start_event_created_at.to_datetime.in_time_zone) %>
    <br>
    <small class="text-muted"><%= time_ago_in_words(category.last_start_event_created_at.to_datetime) %> <%= I18n.t('cron_monitor.ago') %></small>
  <% else %>
    Never
  <% end %>
</td>
<td>
  <% if category.last_finish_event_created_at.present? %>
    <%= I18n.localize(category.last_finish_event_created_at.to_datetime.in_time_zone) %>
    <br>
    <small class="text-muted"><%= time_ago_in_words(category.last_finish_event_created_at.to_datetime) %> <%= I18n.t('cron_monitor.ago') %></small>
  <% else %>
    Never
  <% end %>
</td>
<td>
  <% if category.last_finish_event_created_at.blank? %>
    <%= t("cron_monitor.never_finished") %>
  <% elsif category.last_finish_event_created_at.present? && category.last_start_event_created_at.present? %>
    <% if category.last_finish_event_created_at >= category.last_start_event_created_at %>
      <%= distance_of_time_in_words(category.last_start_event_created_at.to_datetime, category.last_finish_event_created_at.to_datetime) %>
    <% else %>
      <%= t("cron_monitor.started_waiting_for_finish", time_ago: time_ago_in_words(category.last_start_event_created_at.to_datetime)) %>
    <% end %>
  <% else %>
    -
  <% end %>
</td>
<td>
  <% if !category.has_alarm? %>
    No alarm
  <% elsif category.is_running_properly?(last_finish_event_created_at: category.last_finish_event_created_at) %>
    <span class="badge badge-pill badge-success">Yes</span>
    <% if category.last_finish_event_created_at.blank? && !category.should_have_run_yet? %>
      (Shouldn't have run yet)
    <% end %>
  <% else %>
    <span class="badge badge-pill badge-danger">No</span>
    <br>
    <%= I18n.translate(
      "cron_monitor.starting_or_finishing.should_have_run",
      should_have_run_after: I18n.localize(category.should_have_finished_after),
      ran_at_or_never_ran: category.last_finish_event_created_at.blank? ? I18n.translate("cron_monitor.starting_or_finishing.it_never_ran") : I18n.translate("cron_monitor.starting_or_finishing.last_ran_at", datetime: I18n.localize(category.last_finish_event_created_at.to_datetime.in_time_zone)),
      locale: CronMonitor.i18n
    ) %>
  <% end %>
</td>
<td>
  <% if !category.has_alarm? %>
    No alarm
  <% else %>
    <%= I18n.t("cron_monitor.time_frames.#{category.time_frame}", count: category.time_interval) %>
  <% end %>
</td>

app/views/cron_monitor/categories/_category_shared_table_headers.html.erb
<th><%= t("cron_monitor.row_titles.title_html") %></th>
<th><%= t("cron_monitor.row_titles.description_html") %></th>
<th><%= t("cron_monitor.row_titles.last_started_execution_html") %></th>
<th><%= t("cron_monitor.row_titles.last_finished_execution_html") %></th>
<th><%= t("cron_monitor.row_titles.last_duration_html") %></th>
<th><%= t("cron_monitor.row_titles.is_running_properly_html") %></th>
<th><%= t("cron_monitor.row_titles.alarm_html") %></th>

app/views/cron_monitor/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :time_interval %>
    <%= form.text_field :time_interval, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :time_frame %>
    <%= form.select :time_frame, CronMonitor::Category.time_frames.keys, include_blank: 'None', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/cron_monitor/categories/edit.html.erb
<div class="container-fluid">
  <h1>Editing Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Show', @category %> |
  <%= link_to 'Back', categories_path %>
</div>

app/views/cron_monitor/categories/index.html.erb
<div class="container-fluid">

  <p id="notice"><%= notice %></p>

  <h1>Monitors 
    <%= link_to  new_category_path, class: 'btn btn-primary' do %>
      <svg class="bi bi-plus" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M10 5.5a.5.5 0 01.5.5v4a.5.5 0 01-.5.5H6a.5.5 0 010-1h3.5V6a.5.5 0 01.5-.5z" clip-rule="evenodd"></path>
        <path fill-rule="evenodd" d="M9.5 10a.5.5 0 01.5-.5h4a.5.5 0 010 1h-3.5V14a.5.5 0 01-1 0v-4z" clip-rule="evenodd"></path>
      </svg> New Monitor
    <% end %>
  </h1>

  <div class="alert alert-info">
    <%= t("cron_monitor.alert_info_html", delete_older_than: CronMonitor::delete_events_older_than.inspect) %>
  </div>

  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <%= render partial: 'category_shared_table_headers' %>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <%= render partial: 'category_shared_columns', locals: { category: category } %>
          <td><%= link_to t('cron_monitor.btns.show'), category %></td>
          <td><%= link_to t('cron_monitor.btns.edit'), edit_category_path(category) %></td>
          <td><%= link_to t('cron_monitor.btns.destroy'), category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/cron_monitor/categories/new.html.erb
<div class="container-fluid">
  <h1>New monitor</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path %>
</div>

app/views/cron_monitor/categories/show.html.erb
<div class="container-fluid">

  <p id="notice"><%= notice %></p>

  <h1><%= @category.title %> 
    <%= link_to root_path, class: 'btn btn-primary' do %>
      <svg class="bi bi-house" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M9.646 3.146a.5.5 0 01.708 0l6 6a.5.5 0 01.146.354v7a.5.5 0 01-.5.5h-4.5a.5.5 0 01-.5-.5v-4H9v4a.5.5 0 01-.5.5H4a.5.5 0 01-.5-.5v-7a.5.5 0 01.146-.354l6-6zM4.5 9.707V16H8v-4a.5.5 0 01.5-.5h3a.5.5 0 01.5.5v4h3.5V9.707l-5.5-5.5-5.5 5.5z" clip-rule="evenodd"></path>
        <path fill-rule="evenodd" d="M15 4.5V8l-2-2V4.5a.5.5 0 01.5-.5h1a.5.5 0 01.5.5z" clip-rule="evenodd"></path>
      </svg> Home
    <% end %>
  </h1>

  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <%= render partial: 'cron_monitor/categories/category_shared_table_headers' %>
      </tr>
    </thead>

    <tbody>
      <tr>
        <%= render partial: 'cron_monitor/categories/category_shared_columns', locals: { category: @category } %>
      </tr>
    </tbody>
  </table>

  <h2>Events</h2>

  <% if @events.load.any? %>

    <table class="table table-bordered">
      <thead>
        <th>
          Time
        </th>
        <th>Kind</th>
        <th>Data</th>
      </thead>
      <tbody>
        <%= render @events %>
      </tbody>
    </table>


  <% else %>

    <p>There are no events.</p>

  <% end %>

  <%= link_to 'Edit', edit_category_path(@category) %> |
  <%= link_to 'Back', categories_path %>
</div>

app/views/cron_monitor/events/_event.html.erb
<tr>
  <td>
    <%= I18n.localize(event.created_at) %>
    <br>
    <%= time_ago_in_words(event.created_at) %>
  </td>
  <td><%= t("cron_monitor.event_kinds.#{event.kind}") %></td>
  <td>
    <% if event.data.present? %>
      <% event.data.each do |k,v| %>
        <%= k %>: <%= v %>
        <br>
      <% end %>
    <% else %>
      -
    <% end %>
  </td>  
</tr>

app/views/cron_monitor/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_area :data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cron_monitor/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/cron_monitor/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.data %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/cron_monitor/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/cron_monitor/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @event.data %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/cron_monitor/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cron monitor</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "cron_monitor/application", media: "all" %>
  <%= javascript_include_tag "cron_monitor/application" %>
</head>
<body>

<%= yield %>

</body>
</html>